---
title: "Project meeting notes"
format: html
---

## Brief summary of the 2023 paper

#### Problem one: when should each sex arrive or emerge at a resource.

- Males often arrive early, and this has fitness benefits - early monopolisation of females, the chance to mate throughout the mating season etc.

- Females might not want to arrive so early because they don't have to mate so much, mating a lot might be bad, or they want to time arrival/emergence with resource availability for their offspring.

- But if males keep arriving earlier, selection begins to favour earlier arrival in females as well, because the risk of going unmated grows larger.

- This can start a runaway process of earlier and earlier emergence for both sexes. In typical interlocus conflict fashion, males harm females as a biproduct of male-male competition for fertilisations. Absolute female fitness decreases because they evolve to emerge/arrive further from the resource peak.

- The runaway process is eventually stopped when female arrival gets too far away from the resource peak. 

- The result is sexual conflict load, where females are potentially not optimally adapted on either front (finding mates or enjoying lots of resources).

#### Extending this study 

- The current model only considers females that can be inseminated once. What happens if there is polyandry?

- My first thoughts are: females will deplete male sperm stores more rapidly, which might increase the rate of matelessness and select females that arrive earlier. This pushes emergence time further still from the resource. However, now there is sperm competition. If there is last male precedence, then perhaps selection on males to arrive earlier is abated. This is potentially good for the population because the arms race does not drive arrival time as far away from the resource as previously found. 

## 17/10/23

- The West Australian Bush cricket

- Leigh will send through some info on the lifecycle / other relevant stuff like sperm precedence etc.

- They are sperm mixers, with a little bit of second male precedence (I think)

- Resources become available as pollen during the brief flowering season. Heat waves at the end of this period result in very high mortality for adults, but eggs can survive in diapause. 

- Females are polyandrous, but the extent to which they are depends on resource availability.

- If resources are abundant, then females become less interested in mating and sexual selection is stronger in males than females.

- If resources are scarce, females depend upon the male spermatophore for nutrition. Males can only produce one spermatophore every 5-10 days, so they quickly become a limiting resource. Females therefore compete vigorously for males and sexual selection potentially becomes female-biased. 

- This is relevant for protandry because it determines reproductive success in both sexes, but in a way that depends upon resource availability. It is therefore a really nice system to test the models predictions with manipulative experiments. 

- Protandry can be viewed in terms of the length of development. This may be plastic and reflective of the resource availability conditions.

- i.e. if you make resources scarce, then females should plastically shorten their development, whereas if resources are abundant, females should match development with male availability and resource availability. 

- I need more info on the above to make the prediction clear.


# 27/11/23

- The goal is to model the evolution of arrival time in the mating pool, for each sex. 

- In _Kawanaphila nartee_, an Australian bushcricket, arrival time is determined by first-instar to adult development time.   

- Who should arrive first is not so clear in this system, because there is a sex-role reversal in mate competition. When resources are scarce (often at the start of the season), the OSR is female-biased, because males produce spermatophores slowly, keeping them in 'time out' longer than females. Females are also heavily incentivised to mate even if they don't need sperm, because spermatophores provide a valuable source of nutrients.

- When resources are abundant, sex-roles reverse, and intrasexual competition for matings becomes stronger among males than it is among females. Males can produce spermatophores quickly and females don't need the nutrients they provide as much, as alternative feeding opportunities are plentiful. 

- The breeding season ends when the first heatwave hits, which triggers a mass-mortality event. Eggs can survive in a state of diapause. Is there an element of bet-hedging at play here?

- With this and prior theory in mind, the sex that should develop faster depends on the availability of resources. If plentiful, males should emerge first (assuming that early emergence increases mating success/fitness). If scarce, females should develop faster to reap the early arriver rewards. 

- Should one expect a positive correlation between early arrival and female fecundity potential i.e. fast developing females might be in the best condition OR they might have poor fecundity potential because they trade-off body size with mating opportunities.

# 03/04/24

- To model plasticity, we can consider development time as having one of two states, decided by a resource availability threshold. If resources are abundant to the point of exceeding the threshold, females are choosy and thus develop quickly; below the threshold, females compete with other females for matings and therefore develop slowly (or are not selected to mature early).  

- One complication is that resource availability also changes throughout the breeding season - resources are scarce early on and abundant later. This drives within-season plasticity for the sexes.